### ISSUE TITLE
Sort target is incorrectly mapped

### ISSUE THREAD

**Issue by fasaxc** [dims/etcd3-gateway#18]
If I specify `"key"` for the sort target then that gets mapped to `"sort_target": 1` on the API but the docs say that key should be 0:

```
  enum SortTarget {
	KEY = 0;
	VERSION = 1;
	CREATE = 2;
	MOD = 3;
	VALUE = 4;
  }
```

**Comment by dims** [comment]
we need to fix it up here? https://github.com/dims/etcd3-gateway/blob/master/etcd3gw/client.py#L203-L204

**Comment by fasaxc** [comment]
Yeah, looks like the `+ 1`  isn't needed for the sort target
