### ISSUE TITLE
RFE: Add the option to receive data in any encoding format in "put/get"

### ISSUE THREAD

**Issue by lihiwish** [dims/etcd3-gateway#2]
Currently utils._encode/utils._decode allows only utf-8. 
If we want to use binary data (e.g msgpack), get returns an error:
UnicodeDecodeError: 'utf8' codec can't decode byte 0x85 in position 0: invalid start byte

**Comment by dims** [comment]
@lihiwish do you have some changes prototyped? would be great if you could share what you think

**Comment by lihiwish** [comment]
Originally I thought of removing(or making not mandatory) both encode("utf-8") decode("utf-8" ) from [1] and [2]. But I've noticed that it has an effect on increment_last_byte, making all methods of x_prefix not work properly. 

[1] https://github.com/dims/etcd3-gateway/blob/master/etcd3gw/utils.py#L30
[2] https://github.com/dims/etcd3-gateway/blob/master/etcd3gw/utils.py#L41

**Comment by lihiwish** [comment]
I think I managed to find the issue. Looks like watch_prefix encodes range_end twice (once in client, and once in watcher).
I'll test a bit more, and send a PL.
